foodOnline_main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews
urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , views.home , name='home'),
    path('',include('accounts.urls')),
    path('marketplace/',include('marketplace.urls')),
    #cart
    path('cart/',MarketplaceViews.cart ,name='cart'),
    #search
    path('search/',MarketplaceViews.search ,name='search'),
    #checkout
    path('checkout/',MarketplaceViews.checkout ,name='checkout'),
    #Orders
    path('orders/',include('orders.urls')),

    

    
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('place_order/',views.place_order,name='place_order'),
    path('payments/',views.payments,name='payments'),
    path('order_complete/',views.order_complete,name='order_complete'),

]

orders/models.py
from django.db import models
from accounts.models import User
from menu.models import FoodItem
from vendor.models import Vendor
import simplejson as json
# Create your models here.

request_object=''
class Payment(models.Model):
    PAYMENT_METHOD = (
        ('RazorPay','RazorPay'),
    )

    user = models.ForeignKey(User,on_delete=models.CASCADE)
    transaction_id= models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD , max_length=100)
    amount = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id
    
class Order(models.Model):
    STATUS=(
        ('New','New'),
        ('Accepted','Accepted'),
        ('Completed','Completed'),
        ('Cancelled','Cancelled'),
    )

    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    payment=models.ForeignKey(Payment,blank=True,null=True,on_delete=models.SET_NULL)
    #Many to  Many Relationship
    vendor=models.ManyToManyField(Vendor,blank=True)
    order_number = models.CharField(max_length=100)
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    phone=models.CharField(max_length=100,blank=True)
    email=models.EmailField(max_length=100)
    address=models.CharField(max_length=100)
    country=models.CharField(max_length=100,blank=True) 
    state=models.CharField(max_length=15,blank=True)
    city=models.CharField(max_length=50)
    pincode=models.CharField(max_length=10)
    total = models.FloatField()
    #tax_data will be json field - Tax is more than 1 thats y dict
    tax_data = models.JSONField(blank=True,help_text="Data format :{'tax_type':{'tax_percentage':'tax_amount'}}",null=True)
    #total data will be carrying every attribute subtotal tax related to every vendor
    total_data = models.JSONField(blank=True,null=True)

    total_tax=models.FloatField()
    payment_method=models.CharField(max_length=25)
    status=models.CharField(max_length=15,choices=STATUS,default='New')
    is_ordered = models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    #concat fiirst and last name

    def name(self):
        return f'{self.first_name} {self.last_name}'
    
    def order_placed_to(self):
        return ",".join([str(i) for i in self.vendor.all()])
    
    def get_total_by_vendor(self):
        vendor=Vendor.objects.get(user=request_object.user)
        subtotal = 0
        tax=0
        tax_dict={}
        if self.total_data:
            total_data = json.loads(self.total_data)
            data = total_data.get(str(vendor.id))
            print('data inside',data)
            #print(data)

           
            for key,val in data.items():
                subtotal+=float(key)
                #val=val.replace("'",'"')
                val=json.loads(val)
                
                tax_dict.update(val)

                #calculate tax for vendor dashboard

                for i in val:
                    for j in val[i]:
                        tax+=float(val[i][j])
        grand_total = float(subtotal)+ float(tax)
        print('tax_dict',tax_dict)
        print('subtotal',subtotal)
        print('tax',tax)
        print('grand_total',grand_total)

        context={
            'grand_total':grand_total,
        }

        
        #a = vendor.id
        # if self.total_data:
        #     print('Models Test',self.total_data)
        #     #total_data=json.dumps(self.total_data)
        #     data=self.total_data.get(8)
        #     print(data)
        #     #print(total_data)
        return vendor
    
    def __str__(self):
        return self.order_number
    
class OrderedFood(models.Model):
    order=models.ForeignKey(Order , on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    fooditem=models.ForeignKey(FoodItem,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.fooditem

    

accounts/forms.py
from .models import User
from django import forms
from .models import UserProfile
class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    confirm_password = forms.CharField(widget = forms.PasswordInput())

    class Meta:
        model= User
        fields=['first_name','last_name','username','email','password']
    #whenever form is trigger , it using inbuilt pyhton function , in return it gives cleaned_data dictionary
    def clean(self):
        #super will override the cleaned_data
        cleaned_data = super(UserForm , self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password!=confirm_password:
            raise forms.ValidationError('Password does not match')

class UserProfileForm(forms.ModelForm):
    address=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Start Typing..', 'required':'required'}))
    profile_picture = forms.ImageField(widget=forms.FileInput(attrs={'class':'btn btn-info'}))
    cover_photo = forms.ImageField(widget=forms.FileInput(attrs={'class':'btn btn-info'}))
    #latitude = forms.CharField()
    #Making ReadOnly Field 
    latitude =forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    longitude =forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))

    class Meta:
        model=UserProfile
        #fields=['profile_picture','cover_photo','address_line_1','address_line_2','country','state','city','pincode','latitude','longitutde']
        fields=['profile_picture','cover_photo','address','country','state','city','pincode','latitude','longitude']

class UserInfoForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','phone_number']

templates/base.html
<!--If you wanna load static files-->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="{ %static 'css/bootstrap-slider.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
	


	<script src="{% static 'assets/js/modernizr.js' %}"></script>
	<script src="{% static 'assets/js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css'%}">

	
	{% if '/' == request.path or 'profile' in request.path %}
	<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" defer></script>
	{%endif%}
	<script src="{% static 'js/custom.js'%}"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
</head>

<body>

    <!-- Load Navbar-->

    {% include 'includes/navbar.html' %}


    <!-- Load COntent-->
    {% block content%}

    <!-- content goes here-->

    {%endblock%}

    <!--Load footer-->
    {% include 'includes/footer.html' %}
	<!--Main Wrapper-->

		<!-- Header End -->
		<!-- Main Section Start -->
	
	
	

templates/home.html
{%extends 'base.html'%}
{% load static %}

{% block content%}
<div class="main-section">
    <!-- Home Pages Elements Strat -->
    <!-- Main Search Start -->
    <div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'extra-images/bg-image1.jpg'%}) no-repeat center / cover;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="element-title">
                        <h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
                            We are in the business of food<br>our restaurants do</h1>
                        <p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
                            Welcome to My Company :- CEO Bhavesh</p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="main-search fancy bg-holder">
                        <form action="{% url 'search'%}" method="GET">
                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
                                    <div class="field-holder">
                                        <input type="text" name="keyword" placeholder="Resturant name or Food Name">
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
                                    <div class="field-holder">
                                        <ul>
                                            <li class="select-location">
                                                <div class="foodbakery-locations-fields-group foodbakery-focus-out">
                                                    <span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
                                                    
                                                    <input type="text" name="address" id="id_address"  class="location-field-text filter" placeholder="All Locations">
                                                    <input type="hidden" name="lat" value="" id="id_latitude">
                                                    <input type="hidden" name="long" value="" id="id_longitude">

                                                </div>
                                                
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <select name="radius" id ="radius" style="height: 50px;" required>
                                        <option value="">Choose Radius</option>
                                        <option value="5">5km</option>
                                        <option value="10">10km</option>
                                        <option value="15">15km</option>
                                        <option value="20">20km</option>
                                        <option value="25">25km</option>
                                        <option value="50">50km</option>
                                        <option value="100">100km</option>

                                    </select>
                                </div>

                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="field-holder">
                                        <input type="submit" value="Search">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <!-- Main Search End -->
    
    <!-- Top Restarurants Section Start -->
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="element-title align-left">
                        <h2>Top Restaurants</h2>
                        <p>Explore restaurants, bars, and cafés by locality</p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding-right: 0 !important; padding-left: 0 !important;">
                    <div class="company-logo">
                        <ul>
                            {% for vendor in vendors%}
                            <li class="has-border">
                                <figure>
                                    {% if vendor.user_profile.profile_picture%}
                                        <a href="#"><img src="{{vendor.user_profile.profile_picture.url}}" class="attachment-full size-full wp-post-image" alt=""></a>
                                    {%else%}
                                        <a href="#"><img src="{% static 'images/default-profile.png'%}" class="attachment-full size-full wp-post-image" alt=""></a>
                                    {% endif %}
                                    </figure>
                            </li>
                            {% endfor %}    
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Top Restarurants Section End -->
    <!-- Choose From Most Popular Listin Start -->
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="element-title align-center">
                        <h2>Choose From Most Popular Restaurants</h2>
                        <p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="listing fancy">
                        <ul class="row">
                            {% for vendor in vendors%}
                            <li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="list-post featured">
                                    <div class="img-holder">
                                       
                                        <figure><a href="#">
                                            {% if vendor.user_profile.profile_picture%}
                                            <img src="{{vendor.user_profile.profile_picture.url}}" class="img-thumb wp-post-image" alt=""></a></figure>
                                            {%else%}
                                            <img src="{%static 'images/default-profile.png'%}" class="img-thumb wp-post-image" alt=""></a></figure>

                                            {%endif%}
                                        </a>
                                    </figure>
                                            <span class="restaurant-status close">
                                            <em class="bookmarkRibbon"></em>Close
                                        </span>
                                    </div>
                                    <div class="text-holder">
                                        
                                        <div class="post-title">
                                            <h5>
                                                <a href="{% url 'vendor_detail' vendor.vendor_slug%}">{{vendor}}</a>
                                                
                                    </div>
                                    {% if vendor.user_profile.city and vendor.user_profile.state and vendor.user_profile.pincode %}
                                        <span> {{ vendor.user_profile.city}},{{vendor.user_profile.state}},{{vendor.user_profile.pincode}}</span>
                                    {% endif %}

                                    <!--<p>{{vendor.kms}}</p>-->
                                    {% if vendor.kms %}
											<br>
											<span><small><b>{{vendor.kms}} km </b>away</small></span>
										{% endif %}
                                </div>
                                <div class="list-option">
                                    <a href="javascript:void(0);" class="shortlist-btn" data-toggle="modal" data-target="#sign-in">
                                        <i class="icon-heart-o"></i>
                                    </a>
                                </div>
                            
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Choose From Most Popular Listing End -->

    <!-- Home Pages Elements End  -->
</div>
<!-- Main Section End -->
<!-- Footer Start -->

<!-- Footer End -->
</div>

{%endblock%}